version: "3"

services:

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=thinkster_laravel_ng
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysqlBackup:/var/lib/mysql
    ports:
      - "3306:3306"

  myapp:
    tty: true
    image: bitnami/laravel
    depends_on:
      - database
    ports:
      - 8003:3000
    restart: 'always'
    volumes:
      - ./laravel:/app
    command: >
      bash -c "php artisan route:list
      && php artisan key:generate
      && php artisan migrate
      && php artisan migrate:refresh
      && php artisan db:seed
      && php artisan serve --host=0.0.0.0 --port=3000"

  redis:
        image: redis:4.0
        ports:
          - "6379:6379"

volumes: 
  mysqlBackup: