version: "3"

services:

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=thinkster_laravel_ng
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysqlBackup:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - servidor_network

  laravel:
    tty: true
    image: bitnami/laravel
    depends_on:
      - database
    ports:
      - 8003:3000
    restart: 'always'
    volumes:
      - ./laravel:/app
    command: >
      bash -c " composer install 
      && php artisan route:list
      && php artisan migrate
      && php artisan serve --host=0.0.0.0 --port=3000"
    networks:
      - servidor_network

  go:
    image: golang:1.15
    container_name: go_container
    working_dir: /go/src/App
    volumes:
      - ./go:/go/src/App
    ports:
      - "8090:3000"
    restart: 'always'
    networks:
      - servidor_network
    command: >
      bash -c " go get golang.org/x/sys/unix
      && go get -u github.com/kardianos/govendor
      && govendor sync
      && govendor add +external
      && go get -u golang.org/x/crypto/...
      && go get -v github.com/garyburd/redigo/redis
      && go get github.com/pilu/fresh
      && go run main.go "
    depends_on:
      - database
      - redis

  # web:
  #   image: golang:1.15
  #   container_name: go_container
  #   working_dir: /go/src/goApp
  #   volumes:
  #     - ./go:/go/src/goApp
  #   command: >
  #     bash -c " go get -v github.com/garyburd/redigo/redis
  #     && go get github.com/pilu/fresh
  #     && fresh "
  #   ports:
  #     - "8090:8080"
  #   labels:
  #     traefik.backend: "web"
  #     traefik.frontend.rule: "PathPrefix:/"
  #   depends_on:
  #     - database
  #     - redis
  #   networks:
  #     - servidor_network

  # traefik:
  #   image: traefik:v2.0
  #   container_name: traefik_container
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./traefik/traefik.yml:/etc/traefik/traefik.yml
  #   networks:
  #     - servidor_network

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    networks:
      - servidor_network

networks:
  servidor_network:

networks:
  servidor_network:

volumes:
  mysqlBackup:
  redisData: