version: "3"

services:
  go:
    image: golang:1.15
    container_name: go_container
    ports:
      - "8090:8080"
    # working_dir: /go/src/javiersoler
    # volumes:
    #   - ./go:/go/src/javiersoler